# Generated by Django 6.0.4 on 2026-04-27 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20, unique=True)),
                ('capacite', models.IntegerField()),
                ('campus', models.CharField(choices=[('principal', 'Campus Principal FS'), ('lycee', 'Lycée Classique'), ('cra', 'Face CRA')], default='principal', max_length=20)),
                ('est_disponible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
                'ordering': ['nom'],
            },
        ),
    ]
