# Generated by Django 6.0.4 on 2026-04-30 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matieres', '0001_initial'),
        ('salles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploiDuTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semaine_debut', models.DateField()),
                ('semaine_fin', models.DateField()),
                ('semestre', models.CharField(choices=[('1', 'Semestre 1'), ('2', 'Semestre 2')], default='1', max_length=1)),
                ('annee_academique', models.CharField(default='2025-2026', max_length=9)),
                ('est_publie', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Emploi du Temps',
                'verbose_name_plural': 'Emplois du Temps',
                'ordering': ['-semaine_debut'],
            },
        ),
        migrations.CreateModel(
            name='Creneau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi')], max_length=10)),
                ('heure_debut', models.CharField(choices=[('07:30', '7h30'), ('10:15', '10h15'), ('13:00', '13h00'), ('15:45', '15h45')], max_length=5)),
                ('heure_fin', models.CharField(choices=[('10:00', '10h00'), ('12:45', '12h45'), ('15:30', '15h30'), ('18:15', '18h15')], max_length=5)),
                ('genere_auto', models.BooleanField(default=False)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='matieres.matiere')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='salles.salle')),
                ('emploi_du_temps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='plannings.emploidutemps')),
            ],
            options={
                'verbose_name': 'Créneau',
                'verbose_name_plural': 'Créneaux',
                'ordering': ['jour', 'heure_debut'],
                'constraints': [models.UniqueConstraint(fields=('emploi_du_temps', 'salle', 'jour', 'heure_debut'), name='unique_salle_creneau'), models.UniqueConstraint(fields=('emploi_du_temps', 'matiere', 'jour', 'heure_debut'), name='unique_enseignant_creneau')],
            },
        ),
    ]
