# Generated by Django 6.0.4 on 2026-05-08 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignants', '0001_initial'),
        ('filieres', '0002_filiere_campus'),
        ('matieres', '0001_initial'),
        ('plannings', '0001_initial'),
        ('salles', '0002_campus_alter_salle_campus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emploidutemps',
            options={'ordering': ['-semaine_debut', 'type_planning'], 'verbose_name': 'Emploi du Temps', 'verbose_name_plural': 'Emplois du Temps'},
        ),
        migrations.AddField(
            model_name='emploidutemps',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emplois_du_temps', to='salles.campus'),
        ),
        migrations.AddField(
            model_name='emploidutemps',
            name='type_planning',
            field=models.CharField(choices=[('cours', 'Cours'), ('examen', 'Examen'), ('rattrapage', 'Rattrapage')], default='cours', max_length=15),
        ),
        migrations.CreateModel(
            name='CreneauExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.DateField()),
                ('heure_debut', models.CharField(choices=[('07:30', '7h30'), ('10:00', '10h00'), ('13:00', '13h00'), ('15:30', '15h30')], max_length=5)),
                ('heure_fin', models.CharField(choices=[('09:30', '9h30'), ('12:00', '12h00'), ('15:00', '15h00'), ('17:30', '17h30')], max_length=5)),
                ('code_matiere', models.CharField(max_length=20)),
                ('intitule', models.CharField(max_length=200)),
                ('chef_salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chef_salles', to='enseignants.enseignant')),
                ('emploi_du_temps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux_examen', to='plannings.emploidutemps')),
                ('filiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creneaux_examen', to='filieres.filiere')),
                ('matiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creneaux_examen', to='matieres.matiere')),
                ('niveau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creneaux_examen', to='filieres.niveau')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux_examen', to='salles.salle')),
                ('surveillants', models.ManyToManyField(blank=True, related_name='surveillances', to='enseignants.enseignant')),
            ],
            options={
                'verbose_name': 'Créneau Examen',
                'verbose_name_plural': 'Créneaux Examen',
                'ordering': ['jour', 'heure_debut', 'salle__nom'],
                'constraints': [models.UniqueConstraint(fields=('emploi_du_temps', 'salle', 'jour', 'heure_debut'), name='unique_salle_examen')],
            },
        ),
    ]
