# Generated by Django 6.0.4 on 2026-05-11 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planification', '0001_initial'),
        ('plannings', '0002_alter_emploidutemps_options_emploidutemps_campus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emploidutemps',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emplois_du_temps', to='planification.sessionplanification'),
        ),
    ]
