# Generated by Django 6.0.4 on 2026-05-11 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filieres', '0002_filiere_campus'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionPlanification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text="Ex: 'Semaine du 18 au 23 mai 2026'", max_length=120)),
                ('semaine_debut', models.DateField()),
                ('semaine_fin', models.DateField()),
                ('semestre', models.CharField(choices=[('1', 'Semestre 1'), ('2', 'Semestre 2')], default='1', max_length=1)),
                ('annee_academique', models.CharField(default='2025-2026', max_length=9)),
                ('etat', models.CharField(choices=[('collecte', 'Collecte des programmes'), ('pret', 'Prêt à générer'), ('genere', 'Planning généré'), ('publie', 'Publié'), ('archive', 'Archivé')], default='collecte', max_length=15)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('genere_le', models.DateTimeField(blank=True, null=True)),
                ('publie_le', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Session de planification',
                'verbose_name_plural': 'Sessions de planification',
                'ordering': ['-semaine_debut'],
                'constraints': [models.UniqueConstraint(fields=('semaine_debut', 'semestre', 'annee_academique'), name='session_unique_par_semaine')],
            },
        ),
        migrations.CreateModel(
            name='ImportDepartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_import', models.DateTimeField(blank=True, null=True)),
                ('fichier_nom', models.CharField(blank=True, max_length=255)),
                ('nb_matieres', models.IntegerField(default=0)),
                ('nb_erreurs', models.IntegerField(default=0)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports_planification', to='filieres.departement')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='planification.sessionplanification')),
            ],
            options={
                'verbose_name': 'Import département',
                'verbose_name_plural': 'Imports département',
                'ordering': ['session', 'departement__code'],
                'constraints': [models.UniqueConstraint(fields=('session', 'departement'), name='import_unique_par_session_dept')],
            },
        ),
    ]
