# Generated by Django 6.0.4 on 2026-04-30 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enseignants', '0001_initial'),
        ('filieres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('intitule', models.CharField(max_length=200)),
                ('type_seance', models.CharField(choices=[('CM', 'Cours Magistral'), ('TD', 'Travaux Dirigés'), ('TP', 'Travaux Pratiques')], default='CM', max_length=5)),
                ('volume_horaire', models.FloatField(default=2.5)),
                ('enseignant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matieres', to='enseignants.enseignant')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='filieres.niveau')),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'ordering': ['code'],
            },
        ),
    ]
