# Generated by Django 6.0.4 on 2026-05-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignants', '0001_initial'),
        ('filieres', '0002_filiere_campus'),
        ('matieres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='matiere',
            constraint=models.UniqueConstraint(fields=('code', 'niveau'), name='matiere_code_unique_par_niveau'),
        ),
    ]
