# Generated by Django 6.0.4 on 2026-05-11 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matieres', '0002_alter_matiere_code_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='matiere',
            name='matiere_code_unique_par_niveau',
        ),
    ]
