# Generated by Django 6.0.4 on 2026-05-11 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignants', '0001_initial'),
        ('filieres', '0002_filiere_campus'),
        ('matieres', '0003_remove_matiere_matiere_code_unique_par_niveau'),
        ('planification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='planification.sessionplanification'),
        ),
        migrations.AddConstraint(
            model_name='matiere',
            constraint=models.UniqueConstraint(fields=('code', 'niveau', 'session'), name='matiere_code_unique_par_niveau_session'),
        ),
    ]
