# Generated by Django 6.0.4 on 2026-04-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filieres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('grade', models.CharField(choices=[('Dr', 'Docteur'), ('Pr', 'Professeur'), ('Ing', 'Ingénieur'), ('M', 'Monsieur/Madame')], default='Dr', max_length=5)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('specialite', models.CharField(blank=True, max_length=100)),
                ('est_actif', models.BooleanField(default=True)),
                ('departements', models.ManyToManyField(blank=True, related_name='enseignants', to='filieres.departement')),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
