# Generated by Django 5.1.15 on 2026-05-23 22:09

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=20, unique=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Année académique',
                'verbose_name_plural': 'Années académiques',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('ville', models.CharField(choices=[('EBOLOWA', 'Ébolowa'), ('MONATELE', 'Monatélé')], max_length=20)),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campus',
                'ordering': ['ville', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('DAR', 'Division des Affaires Académiques'), ('CHEF_DEPT', 'Chef de département')], help_text='Rôle fonctionnel (DAR ou CHEF_DEPT).', max_length=20)),
                ('grade', models.CharField(blank=True, choices=[('DR', 'Dr'), ('PR', 'Pr'), ('M', 'M'), ('MME', 'Mme'), ('ING', 'Ing')], help_text='Grade académique du chef (Dr, Pr, M, Mme, Ing).', max_length=10)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('departement', models.ForeignKey(blank=True, help_text="Département dont l'utilisateur est chef (CHEF_DEPT uniquement).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chefs', to='core.departement')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('grade', models.CharField(choices=[('DR', 'Dr'), ('PR', 'Pr'), ('M', 'M'), ('MME', 'Mme'), ('ING', 'Ing')], max_length=10)),
                ('departements', models.ManyToManyField(blank=True, related_name='enseignants', to='core.departement')),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('niveau', models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2')], max_length=10)),
                ('ville', models.CharField(choices=[('EBOLOWA', 'Ébolowa'), ('MONATELE', 'Monatélé')], max_length=20)),
                ('effectif', models.IntegerField(default=0)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='core.departement')),
            ],
            options={
                'verbose_name': 'Filière',
                'verbose_name_plural': 'Filières',
                'ordering': ['code', 'niveau', 'ville'],
            },
        ),
        migrations.CreateModel(
            name='ImportPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='imports/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('statut_parsing', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('OK', 'Réussi'), ('AVEC_ERREURS', 'Réussi avec erreurs'), ('ECHEC', 'Échec')], default='EN_ATTENTE', max_length=20)),
                ('rapport_parsing', models.JSONField(blank=True, default=dict)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='core.departement')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports_envoyes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Import de planning',
                'verbose_name_plural': 'Imports de planning',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DemandeCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effectif_declare', models.IntegerField()),
                ('jour', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi')])),
                ('creneau', models.IntegerField(choices=[(0, '7h30-10h00'), (1, '10h15-12h45'), (2, '13h00-15h30'), (3, '15h45-18h15')])),
                ('type_cours', models.CharField(choices=[('CM', 'Cours magistral'), ('TD', 'Travaux dirigés'), ('TP', 'Travaux pratiques'), ('SEMINAIRE', 'Séminaire'), ('PROJET', 'Projet')], default='CM', max_length=20)),
                ('observations', models.TextField(blank=True)),
                ('enseignant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='core.enseignant')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='core.filiere')),
                ('import_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='core.importplanning')),
            ],
            options={
                'verbose_name': 'Demande de cours',
                'verbose_name_plural': 'Demandes de cours',
                'ordering': ['filiere', 'jour', 'creneau'],
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('capacite', models.IntegerField()),
                ('type_salle', models.CharField(choices=[('COURS', 'Cours classique'), ('TP', 'Travaux pratiques'), ('MULTIMEDIA', 'Multimédia'), ('AMPHI', 'Amphithéâtre'), ('TERRAIN', 'Terrain'), ('LABO', 'Laboratoire'), ('BUREAU', 'Bureau')], max_length=30)),
                ('disponible', models.BooleanField(default=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salles', to='core.campus')),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
                'ordering': ['campus', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Semaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(help_text='Lundi de la semaine.')),
                ('date_fin', models.DateField(help_text='Samedi de la semaine.')),
                ('semestre', models.IntegerField(choices=[(1, 'Semestre 1'), (2, 'Semestre 2')])),
                ('statut', models.CharField(choices=[('DRAFT', 'Brouillon'), ('IMPORTS_OUVERTS', 'Imports ouverts'), ('IMPORTS_CLOTURES', 'Imports clôturés'), ('GENERE', 'Planning généré'), ('PUBLIE', 'Publié')], default='DRAFT', max_length=25)),
                ('numero_reference', models.CharField(blank=True, max_length=50)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semaines', to='core.anneeacademique')),
            ],
            options={
                'verbose_name': 'Semaine',
                'verbose_name_plural': 'Semaines',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='ImportPlanningHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='imports/archives/%Y/%m/')),
                ('uploaded_at', models.DateTimeField()),
                ('remplace_le', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField(default=1)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports_historiques', to='core.departement')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('semaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports_historiques', to='core.semaine')),
            ],
            options={
                'verbose_name': 'Import (archive)',
                'verbose_name_plural': 'Imports (archives)',
                'ordering': ['-remplace_le'],
            },
        ),
        migrations.AddField(
            model_name='importplanning',
            name='semaine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='core.semaine'),
        ),
        migrations.CreateModel(
            name='ArchivePlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_pdf', models.FileField(upload_to='archives/pdf/%Y/%m/')),
                ('fichier_docx', models.FileField(blank=True, upload_to='archives/docx/%Y/%m/')),
                ('exporte_le', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField(default=1)),
                ('exporte_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exports', to=settings.AUTH_USER_MODEL)),
                ('semaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='core.semaine')),
            ],
            options={
                'verbose_name': 'Archive de planning',
                'verbose_name_plural': 'Archives de planning',
                'ordering': ['-exporte_le'],
            },
        ),
        migrations.CreateModel(
            name='UE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('intitule', models.CharField(max_length=200)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ues', to='core.filiere')),
            ],
            options={
                'verbose_name': 'UE',
                'verbose_name_plural': 'UE',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi')])),
                ('creneau', models.IntegerField(choices=[(0, '7h30-10h00'), (1, '10h15-12h45'), (2, '13h00-15h30'), (3, '15h45-18h15')])),
                ('type_cours', models.CharField(choices=[('CM', 'Cours magistral'), ('TD', 'Travaux dirigés'), ('TP', 'Travaux pratiques'), ('SEMINAIRE', 'Séminaire'), ('PROJET', 'Projet')], max_length=20)),
                ('modifie_manuellement', models.BooleanField(default=False)),
                ('modifie_le', models.DateTimeField(blank=True, null=True)),
                ('demande_origine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances', to='core.demandecours')),
                ('enseignant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances', to='core.enseignant')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='core.filiere')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances_modifiees', to=settings.AUTH_USER_MODEL)),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='core.salle')),
                ('semaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='core.semaine')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='core.ue')),
            ],
            options={
                'verbose_name': 'Séance',
                'verbose_name_plural': 'Séances',
                'ordering': ['semaine', 'jour', 'creneau'],
            },
        ),
        migrations.AddField(
            model_name='demandecours',
            name='ue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='core.ue'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'DAR')), fields=('role',), name='unique_dar_account'),
        ),
        migrations.AlterUniqueTogether(
            name='enseignant',
            unique_together={('nom', 'grade')},
        ),
        migrations.AlterUniqueTogether(
            name='filiere',
            unique_together={('code', 'niveau', 'ville')},
        ),
        migrations.AlterUniqueTogether(
            name='salle',
            unique_together={('nom', 'campus')},
        ),
        migrations.AlterUniqueTogether(
            name='importplanning',
            unique_together={('semaine', 'departement')},
        ),
        migrations.AddConstraint(
            model_name='seance',
            constraint=models.UniqueConstraint(fields=('semaine', 'salle', 'jour', 'creneau'), name='seance_salle_unique'),
        ),
        migrations.AddConstraint(
            model_name='seance',
            constraint=models.UniqueConstraint(fields=('semaine', 'filiere', 'jour', 'creneau'), name='seance_filiere_unique'),
        ),
    ]
