# Generated by Django 5.1.15 on 2026-05-28 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filiere',
            name='campus_obligatoire',
            field=models.ForeignKey(blank=True, help_text='Optionnel : force toutes les séances de cette filière dans ce campus.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filieres_forcees', to='core.campus'),
        ),
    ]
