# Generated by Django 5.1.15 on 2026-05-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_filiere_campus_obligatoire'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='actif',
            field=models.BooleanField(default=True, help_text="Décocher pour désactiver l'enseignant (indisponible, congé, départ). Un enseignant inactif n'est plus proposé pour de nouvelles affectations."),
        ),
    ]
