# Generated by Django 5.1.15 on 2026-05-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_enseignant_actif'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='statut',
            field=models.CharField(choices=[('PERMANENT', 'Permanent'), ('VACATAIRE', 'Vacataire')], default='PERMANENT', help_text='Les vacataires sont prioritaires lors de la génération du planning.', max_length=12),
        ),
    ]
