# Generated by Django 5.1.15 on 2026-05-29 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_enseignant_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IMPORTS_OUVERTS', 'Imports ouverts'), ('IMPORTS_CLOTURES', 'Imports clôturés'), ('PLANNING_PUBLIE', 'Planning publié'), ('PLANNING_RECU', 'Planning reçu'), ('COMPTE_CREE', 'Compte créé'), ('MOT_DE_PASSE_RESET', 'Mot de passe réinitialisé')], max_length=30)),
                ('titre', models.CharField(max_length=160)),
                ('message', models.TextField(blank=True)),
                ('lien', models.CharField(blank=True, max_length=200)),
                ('lu', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('semaine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='core.semaine')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['destinataire', 'lu', '-created_at'], name='core_notifi_destina_0e66d7_idx')],
            },
        ),
    ]
