# Generated by Django 5.1.15 on 2026-05-30 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndisponibiliteEnseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RECURRENTE', 'Récurrente'), ('PONCTUELLE', 'Ponctuelle')], max_length=12)),
                ('jour', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi')])),
                ('creneau', models.IntegerField(blank=True, choices=[(0, '7h30-10h00'), (1, '10h15-12h45'), (2, '13h00-15h30'), (3, '15h45-18h15')], help_text='Vide = toute la journée.', null=True)),
                ('motif', models.CharField(blank=True, max_length=200)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indisponibilites_creees', to=settings.AUTH_USER_MODEL)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indisponibilites', to='core.enseignant')),
                ('semaine', models.ForeignKey(blank=True, help_text='Renseignée pour une indisponibilité ponctuelle.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indisponibilites', to='core.semaine')),
            ],
            options={
                'verbose_name': 'Indisponibilité enseignant',
                'verbose_name_plural': 'Indisponibilités enseignants',
                'ordering': ['-cree_le'],
                'indexes': [models.Index(fields=['enseignant', 'jour'], name='core_indisp_enseign_da89c7_idx')],
            },
        ),
    ]
