# Generated by Django 5.1.15 on 2026-05-31 19:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_indisponibiliteenseignant'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='matricule',
            field=models.CharField(blank=True, help_text='Matricule officiel des permanents : 7 chiffres + 1 lettre (ex. 0777888A). Laisser vide pour les vacataires.', max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{7}[A-Za-z]$', "Format de matricule invalide : 7 chiffres suivis d'une lettre (ex. 0777888A).")]),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('IMPORTS_OUVERTS', 'Imports ouverts'), ('IMPORTS_CLOTURES', 'Imports clôturés'), ('PLANNING_PUBLIE', 'Planning publié'), ('PLANNING_RECU', 'Planning reçu'), ('COMPTE_CREE', 'Compte créé'), ('MOT_DE_PASSE_RESET', 'Mot de passe réinitialisé'), ('ABSENCE_SIGNALEE', 'Absence signalée')], max_length=30),
        ),
    ]
