# Generated by Django 5.1.15 on 2026-06-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_enseignant_matricule_alter_notification_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='seance',
            name='seance_salle_unique',
        ),
        migrations.AddField(
            model_name='seance',
            name='salle_partageable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='seance',
            constraint=models.UniqueConstraint(condition=models.Q(('salle_partageable', False)), fields=('semaine', 'salle', 'jour', 'creneau'), name='seance_salle_unique'),
        ),
    ]
