# Generated by Django 5.1.15 on 2026-07-04 21:32

import random

from django.db import migrations, models


def seed_credits(apps, schema_editor):
    """Attribue un nombre de crédits (3 ou 6, valeurs FS) aux UE déjà
    enregistrées, qui n'avaient pas encore ce champ."""
    UE = apps.get_model('core', 'UE')
    for ue in UE.objects.all():
        ue.credits = random.choice([3, 6])
        ue.save(update_fields=['credits'])


def noop(apps, schema_editor):
    """Rien à faire en arrière : la colonne est simplement supprimée."""


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_seance_seance_salle_unique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ue',
            name='credits',
            field=models.PositiveSmallIntegerField(choices=[(3, '3 crédits'), (6, '6 crédits')], default=6, help_text='Nombre de crédits de l’UE (3 ou 6 en FS).'),
        ),
        migrations.RunPython(seed_credits, noop),
    ]
