# Generated by Django 6.0.4 on 2026-05-08 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filieres', '0001_initial'),
        ('salles', '0002_campus_alter_salle_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='filiere',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filieres', to='salles.campus'),
        ),
    ]
